version: "3"

services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $HOME/nzbget/config:/config
      - $HOME/nzbget/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6789:6789
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker$HOME/plex
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - $HOME/plex/config:/config
      - $HOME/plex/tvseries:/data/tvshows
      - $HOME/plex/movies:/data/movies
      - $HOME/plex/transcode:/transcode
    restart: unless-stopped

networks:
  vpn-network:
    external: true
