version: "3"

services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Dublin
    volumes:
      - $HOME/storage/config/nzbget:/config
      - $HOME/storage/usenet:/data/usenet
    ports:
      - 6789:6789
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - VERSION=docker
      - TZ=Europe/Dublin
    volumes:
      - $HOME/storage/config/plex:/config
      - $HOME/storage/media:/data/media
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Dublin
    volumes:
      - $HOME/storage/config/radarr:/config
      - $HOME/storage:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Dublin
    volumes:
      - $HOME/storage/config/sonarr:/config
      - $HOME/storage:/data
    ports:
      - 8989:8989
    restart: unless-stopped
