version: "3"

services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - $HOME/storage/nzbget/config:/config
      - $HOME/storage/nzbget/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Dublin
    volumes:
      - $HOME/storage/plex/config:/config
      - $HOME/storage/media/tv:/tvshows
      - $HOME/storage/media/movies:/movies
      - $HOME/storage/plex/transcode:/transcode
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - $HOME/storage/radarr/config:/config
      - $HOME/storage/media/movies:/movies
      - $HOME/storage/nzbget/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - $HOME/storage/sonarr/config:/config
      - $HOME/storage/media/tv:/tv
      - $HOME/storage/nzbget/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
