version: "3"

services:
  openvpn:
    container_name: openvpn
    image: mjenz/rpi-openvpn
    ports:
      - "1194:1194/udp"
    networks:
      vpn-network:
        ipv4_address: 172.16.68.61
    volumes:
      - $PWD/openvpn/:/etc/openvpn/
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      vpn-network:
        ipv4_address: 172.16.68.62
    environment:
      WEBPASSWORD: 'REDACTED'
    volumes:
       - $PWD/pihole/:/etc/pihole/
       - $PWD/pihole/dnsmasq.d/:/etc/dnsmasq.d/
       - /etc/localtime:/etc/localtime:ro
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi3-homeassistant
    volumes:
      - $PWD/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: always

networks:
  vpn-network:
    external: true
