# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-docker-compose", "vagrant-disksize"]
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "millennium-falcon"

  config.disksize.size = '50GB'

  config.vm.network "public_network", bridge: "en0: Ethernet", mac: "080027B6BF51"
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 8083, host: 8083
  config.vm.network "forwarded_port", guest: 8084, host: 8084

  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "3072"
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
    vb.customize ["modifyvm", :id, "--usbxhci", "on"]
    vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'STORAGE', '--vendorid', '0x0080', '--productid', '0x0578']
  end

  config.vm.provision :shell, inline: "mkdir -p /home/vagrant/storage"
  config.vm.provision :shell, inline: "sudo mount --uuid c9becf2f-5e58-4413-a7bc-15e88c4147bf -o defaults -t ext4 /home/vagrant/storage"
  # config.vm.provision :shell, inline: "echo \"UUID=e1699679-7fab-43df-8de0-cb8e602b83c4 /home/vagrant/storage ext4 defaults 0 1\" > /etc/fstab && sudo mount -a"
  config.vm.provision :shell, inline: "chown -R vagrant:vagrant /home/vagrant/storage"
  config.vm.provision :docker
  config.vm.provision :docker_compose
  config.vm.provision :shell, inline: "docker-compose up -d -f /vagrant/docker-compose.yaml --force-recreate"
end
