version: "3"

services:
  openvpn:
    container_name: openvpn
    image: mjenz/rpi-openvpn
    ports:
      - "1194:1194/udp"
    volumes:
      - $HOME/openvpn/:/etc/openvpn/
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      WEBPASSWORD: 'REDACTED'
    volumes:
       - $HOME/pihole/:/etc/pihole/
       - $HOME/pihole/dnsmasq.d/:/etc/dnsmasq.d/
       - /etc/localtime:/etc/localtime:ro
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi3-homeassistant
    volumes:
      - $HOME/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
    restart: always
